spring.application.name=springSecurity

spring.security.user.name=Minakshi
spring.security.user.password=123456

spring.datasource.url=jdbc:mysql://localhost:3306/secure
spring.jpa.show-sql=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
